server:
  port: 10010

spring:
  application:
    name: onlineUml-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10080/eureka
    registry-fetch-interval-seconds: 5  # 拉取服务间隔时间5s
#  instance:
#    prefer-ip-address: true

zuul:
  prefix: /api
  routes:
    item-service: /item/**  # 路由到图片项的微服务