server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/uml?useUnicode=true&characterEncodeing=utf&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      maximum-pool-size: 30
#      minimum-idle: 10
#  rabbitmq:
#    host: 192.168.1.100
#    username: onlineUml
#    password: onlineUml
#    virtual-host: /onlineUml
#    template:
#      exchange: onlineUml.item.exchange
#    publisher-confirms: true

  cloud:        #必须要加，不然服务起不来
    refresh:
      refreshable: none

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10080/eureka
  instance:
#    prefer-ip-address: true     #显示服务的ip地址
#    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

# 通用 Mapper 配置
#mapper:
#  identity: MYSQL
#  not-empty: false


#显示sql语句
mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  type-aliases-package: com.onlineUml.item.pojo  #mybatis要扫描的pojo对象的包（在interface模块中）